language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=2.4.10
  - CAKE_VERSION=2.5.3
  - CAKE_VERSION=master

install:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../cakephp-file-storage-behavior plugins/CakeFileStorage
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
  - sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit"

script:
  - ./lib/Cake/Console/cake test CakeFileStorage AllTests --stderr